sketch-hq/SketchAPI

- README.md
- Source/Application.js
- Source/Artboard.js
- Source/Document.js
- Source/Group.js
- Source/Image.js
- Source/Layer.js
- Source/Page.js
- Source/Rectangle.js
- Source/Selection.js
- Source/Shape.js
- Source/Text.js
- Source/WrappedObject.js
- header.js
Code review for Add esdoc comments to the existing JS API code (#9532):
> As new API code is written, esdoc comments should always be added as part of the process.
> 
> However, we also need to run through the existing API code and add comments to it.
> 
Connect to BohemianCoding/Sketch#9532.
> Code Review: Add esdoc comments to the existing JS API code (#9532)

- Source/Application.js
- Source/Artboard.js
- Source/Document.js
- Source/Group.js
- Source/Image.js
- Source/Layer.js
- Source/Page.js
- Source/Rectangle.js
- Source/Selection.js
- Source/Shape.js
- Source/Tester.js
- Source/Text.js
- Source/WrappedObject.js
Code review for JavaScript based unit tests for the API (#8201):
> As mentioned on #3430. Ping @samdeane to keep him on the loop.
> 
> Things to decide:
> 
> - shall we use an existing testing library ([Mocha.js](http://mochajs.org) seems to be a crowd favourite), or do we roll our own.
> - how do we integrate that with our build process (a failing JS test should break the build)
Connect to BohemianCoding/Sketch#8201.
> Code Review: JavaScript based unit tests for the API (#8201)

- Source/Document.js
- Source/Group.js
- Source/Layer.js
- Source/Rectangle.js
- Source/Selection.js
- Source/Shape.js
- Source/Style.js
- Source/Text.js
- Source/WrappedObject.js
Code review for Update Johnnie’s text utilities plugin to use the api (#10574):
> I'm finding that the best way to drive the development of the JS API is to try to make things using it.
> 
> @randomsequence has a text utilities plugin which is a bit broken - seems like it might be a good candidate for rewriting to use the API, to see what emerges from that.
Connect to BohemianCoding/Sketch#10574.
> Code Review: Update Johnnie’s text utilities plugin to use the api (#10574)

- README.md
- Source/Application.js
- Source/Artboard.js
- Source/Document.js
- Source/Group.js
- Source/Image.js
- Source/Layer.js
- Source/Page.js
- Source/Rectangle.js
- Source/Selection.js
- Source/Shape.js
- Source/Style.js
- Source/Tester.js
- Source/Text.js
- Source/WrappedObject.js
- gulpfile.js
- header.js
Code review for Implement unit tests for the JS API (#10090):
> Issue #8201 has supplied a simple unit testing framework that we can use to test the JS API.
> 
> Now we need to actually fill in the tests...
Connect to BohemianCoding/Sketch#10090.
> Code Review: Implement unit tests for the JS API (#10090)

- Source/Application.js
http://developer.sketchapp.com/examples/code/user-interaction/
> title should be the second argument to displayDialog_withTitle

- Source/Layer.js
- Source/Page.js
Code review for Add support for layer exporting to the javascript API (#10671):
> I think this would be the number one request many people have. In more concrete terms, it'd make Principle happy
Connect to BohemianCoding/Sketch#10671.
> Code Review: Add support for layer exporting to the javascript API (#10671)

- Source/Layer.js
- Source/Selection.js
Code review for isSelected should move out of the model (#8855):
Connect to BohemianCoding/Sketch#8855.
> Code Review: isSelected should move out of the model (#8855)

- Source/Text.js
Code review for Vertical Text Alignment (#13800):
Connect to BohemianCoding/Sketch#13800.
> Code Review: Vertical Text Alignment (#13800)

- Source/Application.js
Connect to BohemianCoding/Sketch#14344
> Reverse parameter order in alert()

- Source/Application.js
- Source/DataSupplier.js
Code review for “Data supplier - Data feed plugins side of data suppliers” (#15052):
Connect to BohemianCoding/Sketch#15052.
> Code Review: Data supplier - Data feed plugins side of data suppliers (#15052)

- .eslintrc.yml
- README.md
- Source/data-supplier/DataSupplier.js
- Source/data-supplier/index.js
- Source/dom/Rectangle.js
- Source/dom/__tests__/Rectangle.test.js
- Source/dom/components/Document.js
- Source/dom/components/Layer.js
- Source/dom/components/__tests__/Layer.test.js
- Source/dom/index.js
- Source/settings/Settings.js
- Source/settings/__tests__/Settings.test.js
- Source/ui/UI.js
- docs/DataSupplier.md
- docs/Document.md
- docs/Rectangle.md
- docs/Settings.md
- docs/UI.md
- docs/wrapped-object.md
Resolves BohemianCoding/Sketch#16878 (“finish polishing SketchAPI for v49”):
Connect to BohemianCoding/Sketch#16878.
Fix #87
> Code Review: finish polishing SketchAPI for v49 (#16878)

- .eslintrc.yml
- Source/dom/components/Document.js
- Source/dom/components/__tests__/Document.test.js
- Source/dom/export.js
- docs/api/Document.md
Resolves BohemianCoding/Sketch#17151 (“findLayerNamed does not work”)
fix #101
> Code Review: getLayerNamed does not work (#17151)

- Source/dom/components/Text.js
set font size with `textLayer.sketchObject.font = NSFont. systemFontOfSize_ (size)`not work
> :bug: set font size

- Source/data-supplier/DataSupplier.js
Connect to BohemianCoding/Sketch#17228
> Fix typo in DataSupplier

- Source/dom/components/Artboard.js
Connect BohemianCoding/Sketch#17202
Fix #111
> Code Review: Fix Artboard.adjustToFit in SketchAPI (#17202)

- Source/dom/components/Page.js
It throws error when create a page.
And I wonder if it is neccesary to init a page with a frame
`initWIthFram(new Rectange(0, 0, 100, 100).asRect())`
> :bug: addPage is not a function of MSDocument instance

- Source/dom/components/Shape.js
Resolves BohemianCoding/Sketch#17367
>  fix adding a path layer when accessing a shape

- CHANGELOG.json
- Source/dom/Rectangle.js
- Source/dom/components/Layer.js
- Source/dom/components/__tests__/Layer.test.js
- tsconfig.json
> fix rectangle setters

- Source/ui/UI.js
Fix BohemianCoding/Sketch#17424
> plugins.png now used for dialog #17424

- circle.yml
- dangerfile.ts
- package-lock.json
- package.json
- tsconfig.json
> Stricter dangerCI

- docs/guides/preferences.md
The "in conjunction with"... section may be over the top, but it's fundamental to my workflow, and idk what the average Sketch plugin developer's familiarity with unix is, so I erred on the side of overly informative.
> add note about entr and restarting sketch during dev

- examples/svgo-export/package.json
- examples/svgo-export/src/svgo-export.js
> fix svgo export example

- Source/dom/components/Shape.js
- Source/dom/components/__tests__/Shape.test.js
- Source/dom/style/Blur.js
- Source/dom/style/Border.js
- Source/dom/style/BorderOptions.js
- Source/dom/style/Fill.js
- Source/dom/style/Gradient.js
- Source/dom/style/Style.js
- Source/dom/style/__tests__/Style.test.js
Resolves BohemianCoding/Sketch#17891
> Code Review: default Shape creates a path that is offset (#17891)

- .eslintrc.yml
- CHANGELOG.json
- Source/dom/components/Library.js
Resolves BohemianCoding/Sketch#18200
> Code Review: missing SketchAPI wrapper for some libraries (#18200)

- docs/api/DataSupplier.md
Code review for BohemianCoding/Sketch#17934 (“Backend changes to data”):
Connect to BohemianCoding/Sketch#17934.
> Code Review: Backend changes to data (#17934)

- CHANGELOG.json
- Source/dom/components/SymbolInstance.js
> fix setting image override

- docs/guides/publishing.md
> fix idents

- CHANGELOG.json
- Source/dom/components/Library.js
> fix getting the wrong lib when multiple share the same id

- CHANGELOG.json
- core-modules/package-lock.json
- core-modules/package.json
fix #206 
fix BohemianCoding/Sketch#18736
> update util core module

- core-modules/package.json
- dangerfile.ts
Resolves BohemianCoding/Sketch#18824
> Code Review: fix package-lock.json mismatch #18824

- CHANGELOG.json
- Source/dom/style/Gradient.js
- Source/dom/style/__tests__/Gradient.test.js
> fix setting the to of a gradient

- CHANGELOG.json
- Source/dom/style/Border.js
- Source/dom/style/Gradient.js
- Source/dom/style/Shadow.js
- Source/dom/style/__tests__/Border.test.js
- Source/dom/style/__tests__/Gradient.test.js
- Source/dom/style/__tests__/Shadow.test.js
- core-modules/package.json
- dangerfile.ts
> fix using 0 as values

- Source/data-supplier/DataSupplier.ts
- types/sketch-internals.d.ts
Code review for BohemianCoding/Sketch#19390 (“Provide way for data supplier plugins to make partial data fulfilment”):
Connect to BohemianCoding/Sketch#19390.
> Code Review: Provide way for data supplier plugins to make partial data fulfilment (#19390)

- Source/dom/layers/Text.js
Code review for BohemianCoding/Sketch#19750 (“Fix Sketch JS API tests for Xcode 10”):
Connect to BohemianCoding/Sketch#19750.
> Code Review: Fix Sketch JS API tests for Xcode 10 (#19750)

- CHANGELOG.json
- Source/dom/models/Document.js
fix #248.
I'm not even going to document the option to force it, it will arrive just in time if the plugin devs mean to do that.
> make sure that we do not overwrite a folder

- Source/dom/style/Style.js
Connect to BohemianCoding/Sketch#20802
> Code Review: 'Choose Text Style' button missing (#20802)

- Source/dom/layers/Text.js
- Source/dom/layers/__tests__/Text.test.js
> fix fragments

- Source/ui/UI.js
fix BohemianCoding/Sketch#21892
> Code Review: Align the input with the button (#21892)

- Source/settings/Settings.js
- Source/settings/__tests__/Settings.test.js
> fix setting undefined on layers

- core-modules/package.json
adds a `path.resourcePath(resourceName)` method which is `command.pluginBundle().urlForResourceNamed(resourceName)` being the scene
Fix #124
> update path module

- CHANGELOG.json
- Source/dom/layers/Artboard.js
- Source/dom/layers/SymbolMaster.js
- Source/dom/layers/__tests__/Artboard.test.js
- docs/api/Artboard.md
- docs/api/SymbolMaster.md
> add background property to Artboard

- CHANGELOG.json
- Source/dom/layers/SymbolInstance.js
- Source/dom/layers/__tests__/SymbolInstance.test.js
- docs/api/SymbolInstance.md
> fix detaching a symbol instance

- Source/dom/WrappedObject.js
- Source/dom/layers/Group.js
- Source/dom/layers/Layer.js
- Source/dom/layers/__tests__/Group.test.js
- Source/dom/layers/__tests__/Layer.test.js
- Source/dom/layers/__tests__/Text.test.js
- Source/dom/models/Document.js
- Source/dom/models/__tests__/ImportableObject.test.js
- Source/dom/style/Style.js
- package-lock.json
- package.json
up till now, if you do `group.layers.push({type: 'Text'})` nothing would happen because even tho the array is mutated, the setter is not called.
Now, everything works as expected.
> hook into the array methods to mutate the owner when mutating the array

- Source/ui/UI.js
connect BohemianCoding/Sketch#22854
> Code Review: Focus issue with User Input dialog (#22854)

- Source/dom/layers/StyledLayer.js
- Source/dom/layers/__tests__/StyledLayer.test.js
- Source/dom/models/SharedStyle.js
- Source/test-utils.ts
> fix sharedStyle when it is remote

- Source/dom/layers/SymbolInstance.js
- Source/dom/layers/SymbolMaster.js
- Source/dom/layers/__tests__/SymbolMaster.test.js
- Source/dom/models/__tests__/Override.test.js
> fix the order of overrides

- CHANGELOG.json
- Source/dom/models/Document.js
- Source/dom/models/Selection.js
- Source/dom/models/__tests__/Document.test.js
- Source/dom/models/__tests__/Selection.test.js
- docs/api/Artboard.md
- docs/api/Document.md
- docs/api/Group.md
- docs/api/HotSpot.md
- docs/api/Image.md
- docs/api/Page.md
- docs/api/Selection.md
- docs/api/Shape.md
- docs/api/ShapePath.md
- docs/api/SymbolInstance.md
- docs/api/SymbolMaster.md
- docs/api/Text.md
> improve selection

- .eslintrc.yml
- CHANGELOG.json
- Source/dom/__tests__/import.test.js
- Source/dom/import.js
- Source/dom/index.js
- Source/dom/layers/Layer.js
- Source/dom/layers/Page.js
- Source/dom/layers/__tests__/Layer.test.js
- Source/dom/models/Document.js
- Source/dom/models/ImageData.js
- Source/dom/models/Selection.js
- Source/dom/models/__tests__/Document.test.js
- Source/dom/models/__tests__/Selection.test.js
- Source/test-utils.ts
- docs/api/Artboard.md
- docs/api/Document.md
- docs/api/Group.md
- docs/api/HotSpot.md
- docs/api/Image.md
- docs/api/Page.md
- docs/api/Selection.md
- docs/api/Shape.md
- docs/api/ShapePath.md
- docs/api/SymbolInstance.md
- docs/api/SymbolMaster.md
- docs/api/Text.md
- docs/api/import.md
ℹ️ Address #366  
⚠️ Requires #372
> File import

- CHANGELOG.json
- Source/dom/layers/Artboard.js
- Source/dom/style/Border.js
- Source/dom/style/Color.js
- Source/dom/style/Fill.js
- Source/dom/style/GradientStop.js
- Source/dom/style/Shadow.js
- Source/dom/style/Text.js
fix BohemianCoding/Sketch#23482
> Code Review: Crash on v53 at MSAssetCollectionViewDataSource highlightAsset:inCollectionView (#23482)

- docs/api/Settings.md
I found a wrong section title. I think that it is because copied and pasted it.
> Fix a wrong section title

- .eslintrc.yml
- CHANGELOG.json
- Source/dom/layers/Page.js
- Source/dom/layers/SymbolInstance.js
- Source/dom/layers/SymbolMaster.js
- Source/dom/layers/__tests__/Artboard.test.js
- Source/dom/layers/__tests__/Group.test.js
- Source/dom/layers/__tests__/HotSpot.test.js
- Source/dom/layers/__tests__/Image.test.js
- Source/dom/layers/__tests__/Page.test.js
- Source/dom/layers/__tests__/Shape.test.js
- Source/dom/layers/__tests__/ShapePath.test.js
- Source/dom/layers/__tests__/Slice.test.js
- Source/dom/layers/__tests__/SymbolInstance.test.js
- Source/dom/layers/__tests__/SymbolMaster.test.js
- Source/dom/layers/__tests__/Text.test.js
- Source/dom/models/Document.js
- Source/dom/models/__tests__/Document.test.js
- Source/test-utils.ts
> `symbolInstance.master` now works on an immutable instance

- Source/dom/models/Document.js
> do no use context as first document choice

- Source/dom/style/Style.js
- docs/api/SharedStyle.md
> add `Unknown` to style type map

- CHANGELOG.json
- Source/dom/layers/Layer.js
- Source/dom/layers/__tests__/Layer.test.js
- docs/api/Layer.md
> layer.index can now be set

- core-modules/package.json
fix BohemianCoding/Sketch#23579
> Code Review: add `stream` and `string_decoder` node polyfills (#23579)

- core-modules/package.json
see https://sketch-friends.slack.com/archives/C5YKGT26B/p1551980013060100
> fix nsdict casting

- core-modules/package.json
fix BohemianCoding/Sketch#23800
> Code Review: Plugins don't execute at all in latest Internal (#23800)

- Source/async/index.ts
- Source/data-supplier/index.ts
- Source/dom/index.js
- Source/index.ts
- Source/settings/index.ts
- Source/ui/index.ts
fix BohemianCoding/Sketch#23888
> Code Review: fix JS API exports (#23888)

- core-modules/package.json
Fix BohemianCoding/Sketch#23989
> Code Review: Crash running script from sketch-dev-tools - Playground (#23989)

- CHANGELOG.json
- Source/dom/style/Fill.js
- Source/dom/style/Style.js
- Source/dom/style/__tests__/Fill.test.js
- docs/api/Style.md
see https://sketchplugins.com/d/1331-setting-a-shapeobject-to-the-new-noise-property-will-crash-sketch
> noise is just a pattern now

- CHANGELOG.json
- Source/dom/layers/StyledLayer.js
- Source/dom/style/Style.js
- Source/dom/style/__tests__/Text.test.js
See https://sketch-friends.slack.com/archives/C5YKGT26B/p1553528782175900
> fix creating a text style on a text layer

- Source/dom/style/Style.js
- core-modules/package.json
Fix BohemianCoding/Sketch#24057
> Code Review: JS console throwing when printing an Error (#24057)

- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- README.md
- docs-website/_config.yml
- docs-website/_posts/2016-05-12-plugin-news.markdown
- docs/api/introduction.md
- docs/guides/sketchtool.md
- examples/hello-world/package.json
- examples/hello-world/src/hello-world.js
- examples/resources/package.json
- examples/resources/src/resources.js
- examples/selection-changed/package.json
- examples/svgo-export/package.json
- examples/svgo-export/src/svgo-export.js
- examples/text-utilities/src/text-utilities.js
> replace `@sketchapp.com` with `@sketch.com`
replace `@bohemiancoding.com` with `@sketch.com`
connects to BohemianCoding/Sketch#23974
> Code Review: Replace `@sketchapp.com` with `@sketch.com` (23974)

- CHANGELOG.json
- Source/dom/models/CurvePoint.js
> fix changing pointType

- CHANGELOG.json
- Source/dom/layers/ShapePath.js
- Source/dom/layers/__tests__/ShapePath.test.js
- Source/dom/models/__tests__/CurvePoint.test.js
- docs/api/ShapePath.md
> do not default to ShapeType.Rectangle when points are specified

- docs-website/_sass/base/_typography.scss
- docs-website/pages/plugins-internal-api.md
- docs-website/pages/plugins-releases-53.md
- docs-website/pages/plugins-releases-54.md
> Add API Release Notes Section

- core-modules/package.json
> update console core module

- CHANGELOG.json
- Source/dom/layers/SymbolMaster.js
- Source/dom/layers/__tests__/Layer.test.js
- docs/api/Layer.md
reported here: https://sketchplugins.com/d/1245-parent-group-or-artboard/3
> fix getParentSymbolMaster for SymbolMaster

- CHANGELOG.json
- Source/dom/layers/Group.js
Fix a bug found by @KevinGutowski in his article: https://medium.com/@kevingutowski/how-to-build-your-first-sketch-plugin-14c0e9e56bf0
> Fix setting layers of a group when the layers already had a parent

- Source/dom/__tests__/export.test.js
- Source/dom/export.js
- Source/dom/layers/Shape.js
- Source/dom/models/__tests__/CurvePoint.test.js
- Source/dom/models/__tests__/Document.test.js
- Source/dom/models/__tests__/ImportableObject.test.js
- Source/dom/models/__tests__/Library.test.js
- package-lock.json
- package.json
fix #495
fix BohemianCoding/Sketch#24552
> Code Review: Export Pages with options break in Sketch 55 Beta (#24552)

- core-modules/package.json
See https://github.com/skpm/console/issues/4
> fix logging MOStruct

- docs/pages/cli-dump.md
Noticed a typo on the Dump JSON data page :)
> Fix typo on Dump JSON data page

- docs/pages/app.md
- docs/pages/plugins-releases-53.md
- docs/pages/plugins-releases-54.md
- docs/pages/plugins-releases-55.md
> Add 55 changes including separate section in URL scheme

- docs/pages/plugins-releases-53.md
> Add closing parenthesis

- docs-website/_includes/scripts.html
- docs-website/_layouts/base.html
- docs-website/_sass/components/_banner-cookieconsent.scss
- docs-website/css/style.scss
- docs-website/js/cookie-consent.js
Connect to: https://github.com/BohemianCoding/MarketingWebsite/issues/63
The PR contains the following:
- Add a tracking code to the base.html layout
- Add a cookie consent banner to the website which links to our general Privacy Policy page.
> Add analytics to developer docs

- CHANGELOG.json
- Source/dom/models/Document.js
- Source/dom/models/__tests__/Document.test.js
- docs/api/Document.md
> Add api for exposing and changing a document's color space

- CHANGELOG.json
- Source/dom/layers/ShapePath.js
- Source/dom/layers/__tests__/ShapePath.test.js
- docs/api/ShapePath.md
> Expose the PointType enum on ShapePath

- CHANGELOG.json
- Source/dom/models/Document.js
> Fixes centerOnLayer not working for nested layers

- docs/pages/cli-export.md
> Add pages paragraph

- README.md
- package-lock.json
> Ignore this PR

- README.md
> You can't see me

- package-lock.json
Fixes the vulnerability reported in https://github.com/BohemianCoding/SketchAPI/network/alert/package-lock.json/set-value/open
> Bump set-value

- CHANGELOG.json
- docs/pages/plugins-document-changes.md
- docs/pages/plugins-manifest.md
> Add docs for onDocumentChanged handler

- docs/pages/file-format-versioning.md
Closes #645 
Updated versions and adjusted copy/structure for clarity.
> Update versioning table

- .eslintrc.yml
- CHANGELOG.json
- Source/dom/index.js
- Source/dom/layers/Artboard.js
- Source/dom/layers/Group.js
- Source/dom/layers/Page.js
- Source/dom/layers/SymbolInstance.js
- Source/dom/layers/__tests__/Group.test.js
- Source/dom/layers/__tests__/SymbolInstance.test.js
- Source/dom/models/Document.js
- Source/dom/models/SmartLayout.js
- docs/api/Group.md
- docs/api/SmartLayout.md
- docs/api/SymbolInstance.md
> Smart layout API

- .eslintrc.yml
- CHANGELOG.json
- Source/dom/style/Text.js
- Source/dom/style/__tests__/Text.test.js
- docs/api/Style.md
> Variable font API

- docs/pages/app.md
> Code Review: Add docs for add-library scheme command (#677)

- CHANGELOG.json
- Source/dom/models/Library.js
- Source/dom/models/__tests__/Library.test.js
- docs/api/Library.md
> update LibraryType enum

- CHANGELOG.json
- Source/dom/models/SharedStyle.js
> Include object in error message

- CHANGELOG.json
- Source/dom/export.js
- Source/dom/models/SharedStyle.js
- docs/pages/plugins-actions.md
> Use the right method for objectFromJSON

- CHANGELOG.json
- Source/dom/layers/SymbolMaster.js
- Source/dom/models/SharedStyle.js
- docs/pages/plugins-actions.md
> Fix for SymbolMaster tests

- CHANGELOG.md
- Source/dom/style/Text.js
Connect sketch-hq/sketch#30153
> Include special handling of 10.15 system fonts

- SketchAPI.xcodeproj/project.pbxproj
- SketchAPI.xcodeproj/xcshareddata/xcschemes/Sketch API.xcscheme
Connect sketch-hq/sketch#30143
Created by `bo pr`.
> Code Review: Xcode 11.5 (#30143)

- docs/pages/plugins-cocoascript.md
Fixes a typo in the documentation
> Fixed typo
