sketch-hq/SketchAPI

Source/Document.js
Source/Text.js

Code review for Convert hello-world plugin example to use API (#9534):
> Wherever possible, our plugins should use the JS API, so that when people copy them, they also use the API.
Connect to BohemianCoding/Sketch#9534.

Code Review: Convert hello-world plugin example to use API (#9534)

---

Source/Application.js
Source/Document.js
Source/Layer.js
Source/Selection.js

Code review for Improve wrapping in JS API (#10163):
> At the moment we've got a function to wrap Sketch objects in JS objects, but it only works if you explicitly tell it what kind of Sketch object you've got. 
> 
> This is fine when you *know*, eg when asking to make a new layer, you know what kind of layer you want. It's not so good though when doing something like iterating a collection of layers, where all you know is that they are layers, but what you actually need is to make a wrapper for each, and have it be a `Text` object for `MSTextLayer`, and `Image` object for `MSBitmapLayer`, and so on.
> 
> This needs to be improved, so that we can give any of the major layer types to `Application` and get back a wrapper object of the right type. 
Connect to BohemianCoding/Sketch#10163.

Code Review: Improve wrapping in JS API (#10163)

---

.gitignore
README.md
gulpfile.js
package.json

I changed the output directory to be within the project repository in `Output/SketchAPI.js` so that everything related to this project is contained within this folder. I also added `Output/` to the `.gitignore` file so the resulting built file won't be committed.
There may be a better name other than `Output` for this folder, the main thing I wanted to accomplish with this PR was for the resulting js file to be within the project folder to keep everything together and not mess with the developer's folder structure outside of the project folder.

Change the output directory for the built SketchAPI.js file

---

Source/Image.js

Code review for “"MSImageData.alloc().initWithImage_convertColorSpace is not a function" in SketchAPI” (#15219):
Connect to BohemianCoding/Sketch#15219.

Code Review: "MSImageData.alloc().initWithImage_convertColorSpace is not a function" in SketchAPI (#15219)

---

Source/settings/Settings.js
Source/settings/__tests__/Settings.test.js
docs/Settings.md

polish the settings API

---

examples/text-utilities/src/text-utilities.js

the example not work
- iterate `document.selectedLayers` throw `TypeError`: `document.selectedLayers.forEach is not a function`
- the enums exported from api turns into object, so the compare by `===` always failed
```javascript
log(typeof sketch.Types.Text) // object
```
- wrap `fills` and `borders` into `style` object when create new Shape

:bug: fix examples/text-utilities

---

docs/api/Layer.md

the `Layer` component is not exposed to the api and we can not create a new layer by calling `new Layer()`

:bug: fix layer document

---

docs/api/Selection.md

1. `selection.clear()` does not need any parameters
1. move iterate method code & add `map` `reduce` method doc

fix some typo in Selection.md

---

Source/dom/Rectangle.js
Source/dom/__tests__/Rectangle.test.js

The former code failed to correctly copy source rectangles whose `x` == `0`, returning a Rectangle with `{ x: nan... }`. It might also be worthwhile to put some checks in place to ensure `NaN` is never possible as the values for any of the rectangle properties.

Fix bug in Rectangle copying functionality

---

docs/guides/actions.md

Message toast wasn’t showing up because the dictionary structure of **context** is slightly different.

Fix onOpenDocument example function

---

.eslintrc.yml
examples/svgo-export/package.json
examples/svgo-export/src/svgo-export.js

* only compress paths, not whole folder
* tidy comments
* print messages to `UI.message`
* make file pass `lint-staged`
I wasn't sure what to do about getting `require('sketch/ui')` to pass `lint-staged`, so let me know if ignoring it is right.

tidy svgo-export example

---

Source/dom/components/Document.js

Before this change, calling `document.save()` without passing a path was throwing the following error:
ObjC method saveDocument: requires 1 argument, but JavaScript passed 0 arguments

fix Document save method when no path is provided

---

Source/settings/Settings.js
Source/settings/__tests__/Settings.test.js
webpack.config.js

#224 
Implicitly convert some common NSObjects to native JS objects to improve stringification when storing settings.

Improve stringification of NSObjects 

---

docs/api/Page.md

Should be "new Page" not "new Artboard" since providing instructions for creating a page.

Fixed typo

---

docs/api/Document.md

This fix replaces the variable of "symbols" for document.getSharedLayerStyles() and document.getSharedTextStyles() with something more relavant; "var layerStyles" and "var textStyles" respectively.

Fix for typo on Document

---

Source/dom/layers/Layer.js
Source/dom/layers/__tests__/Page.test.js
docs/api/Flow.md
docs/api/Selection.md
docs/api/Style.md
docs/api/Text.md
docs/api/wrapped-object.md
examples/svgo-export/README.md

• Fixed spelling of `whether`. At a number of places whether was misspelled as `wether`
• Replaced `a` with `an` wherever required

fix a bunch of spellings

---

.eslintrc.yml
CHANGELOG.json
Source/ui/UI.js
docs/api/UI.md

Fix BohemianCoding/Sketch#20833

Code Review: Polish for MSModalInputSheet (#20833)

---

CHANGELOG.json
Source/dom/layers/Text.js
Source/dom/layers/__tests__/Text.test.js
docs/api/Text.md

Adds `verticalAlignment` and `VerticalAlignment` to `Text`.
I am reading the vertical alignment of text fields in a plugin, and figured that I would make this as it is a small feature that was missing.
Note: As of Sketch 52.3, `MSImmutableTextLayer` appears to not implement a getter for `verticalAlignment`, so as currently written this feature isn't safe. I could add a check to make sure that the property exists, or the PR can wait for an implementation to be added to Sketch.

Add verticalAlignment to Text

---

Source/dom/layers/Text.js
Source/dom/layers/__tests__/Text.test.js
core-modules/package.json

fix BohemianCoding/Sketch#21824

Code Review: polyfill setTimeout in cocoascript (#21824)

---

CHANGELOG.json
Source/dom/WrappedObject.js
Source/dom/layers/Artboard.js
Source/dom/layers/HotSpot.js
Source/dom/layers/Layer.js
Source/dom/layers/Page.js
Source/dom/layers/Slice.js
Source/dom/layers/__tests__/Layer.test.js
docs/api/Group.md
docs/api/Image.md
docs/api/Layer.md
docs/api/Shape.md
docs/api/SymbolInstance.md
docs/api/Text.md

add transform on Layer

---

Source/dom/style/Text.js
Source/dom/style/__tests__/Text.test.js
Source/dom/utils.js

handle floating point in text styles

---

CHANGELOG.json
Source/dom/layers/Layer.js
Source/dom/layers/__tests__/Layer.test.js

Address #376 and allow `layer.duplicate()` to complete even when the initial layer doesn't have a parent.

Allow duplicating a layer without a parent

---

docs/api/Override.md

Overrides are null when an instance is created. Once an instance is pushed into the document, the overrides become available. This is ambiguous in the current documentation and might cost a lot of developer hours.

Updating when overrides are populated

---

.eslintrc.yml
CHANGELOG.json
Source/dom/layers/SymbolInstance.js
Source/dom/layers/__tests__/SymbolInstance.test.js
Source/dom/layers/__tests__/SymbolMaster.test.js
Source/dom/models/DataOverride.js
Source/dom/models/Override.js
Source/dom/models/__tests__/Override.test.js
docs/api/Override.md

selected overrides

---

Source/async/index.ts
Source/data-supplier/index.ts
Source/dom/index.js
Source/index.ts
Source/settings/index.ts
Source/ui/index.ts

fix BohemianCoding/Sketch#23921
Now I'm manually exporting both `module.exports` and `module.exports.default` (which is what `import sketch from 'sketch'` is looking for)

Code Review: Sketch Dev Tools can't be opened (#23921)

---

Source/dom/models/Document.js
Source/dom/models/SharedStyle.js
docs/api/SharedStyle.md

You can only insert local shared styles (eg. not linked to a Library). `document.sharedLayerStyles` returns the foreign shared styles (eg. linked to a Library) concatenated with the local shared styles.
So if you tried to insert a shared style (using `sharedStyles.push`), it would throw an index out of bounds error if there were some foreign shared styles.
Now it won't but if you try to insert a new Shared Style at the beginning (using `unshift` for example), it will end up at the beginning of the local Shared Styles but that might not be the beginning of all the shared styles if there are some foreign.
I don't think there is a perfect solution :(
For that reason, I decided, to de-deprecate `SharedStyle.fromStyle` which is just cleaner when you want to create a shared style and get a …

fix inserting shared styles

---

docs/api/ShapePath.md

It’s super confusing to conflate creating `Shape` objects with `ShapePath`. Hopefully this fix will help people be less confused.

Fix error in Shapepath documentation

---

docs/api/Page.md

Thought it would be better to make a PR rather than an issue for this. When I log `.getSymbolsPage(document)` and there is no Page titled “Symbols”, the method returns `undefined` and not `null`

getSymbolsPage returns `undefined` not `null`

---

Source/dom/models/Selection.js

improve console output for selection

---

examples/hello-world/src/hello-world.js
examples/resources/src/resources.js
examples/text-utilities/src/text-utilities.js

Fix #438 
The reason to disable `no-restricted-syntax` is that because plugins expect an `export default` but I don't want it in the API (and it shares the same eslint config)
The reason to disable `no-new` is because we are not doing anything with the new layers and eslint doesn't like that
The reason to disable `no-param-reassign` is that in this case, that's actually very much what we want to do

fix lint in examples

---

.eslintrc.yml
CHANGELOG.json
Source/dom/models/CurvePoint.js
Source/dom/models/__tests__/CurvePoint.test.js
docs/api/CurvePoint.md

fix #441
For now it's a simple getter because a setter is really complicated and I'm not sure there is a use case for it

add method to check if a CurvePoint is selected

---

docs/api/SharedStyle.md

Explains why some shared style's id can be like `FBFF821E-20F3-48C5-AEDC-89F97A8C2344[D1A683E0-5333-4EBE-977C-48F64F934E99]`

add note about private shared styles

---

CHANGELOG.json
Source/dom/models/Document.js
package.json
webpack.config.js

fix #457 
Babel would tranform `[nativeDocument] = NSApplication.sharedApplication().orderedDocuments()` thinking that it's a proper array but it's not, it's an NSArray so it would throw an error.

return undefined when there is no documents

---

.eslintrc.yml
Source/ui/UI.js

Fixes #315 
I thought it was a little strange to use a `NSCombobox` for this dropdown. That being said, the `NSComboBox` is a bit more useful if you have tons of things to select from.

change NSCombobox to a NSPopUpButton

---

docs/pages/plugins-create-plugin.md
docs/pages/plugins-manifest.md
reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/command.js

I tripped up frequently trying to create a vanilla plugin using the existing manifest.json documentation. Specifically how the manifest interacts with how functions should be declared in a vanilla plugin vs skmp, and the differences between `hanlder` and `handlers`. This is my attempt to improve it for new users.

Improve manifest.json docs

---

webpack.config.js

Ref #513 
Build artefacts are always saved to the build folder in the API repo.
Now that Jenkins uses the same `npm run build` to produce the zipped API bundle, including the API and core modules, this case of building the API in the context of a submodule within the Sketch repo is no longer relevant.

Remove case of API being built as submodule

---

Source/dom/layers/ShapePath.js

Closes BohemianCoding/Sketch#26272
The internal method we use was renamed in 58. The tests were not passing, and now they are, so the fix does not change the tests

Fix for fromSVGPath()

---

docs-website/_sass/helpers/_helpers.scss

This removes a weird space under code blocks that made text pages looks a bit silly.

Tighten the spacing for code blocks

---

core-modules/package.json

some npm packages are checking `process.argv` which should return an array.
`@skpm/process@0.1.4` now returns `["/path/to/Sketch.app", "/path/to/plugin.sketchplugin", context]`

polyfill process.argv

---

docs/api/SharedStyle.md
docs/api/SymbolMaster.md

Identical headings result in ambiguous anchors:
> “Symbol Master > Get the library it was defined in” does actually link to “Shared Style > Get the library it was defined in”

Fixes shared style and symbols docs using same headings

---

docs/pages/cli.md

The old location still has a symlink but actual binary is in `Sketch.app/Contents/MacOS/sketchtool`

Fix sketchtool location

---

Source/dom/layers/Text.js
Source/dom/layers/__tests__/Text.test.js

Mapped the new Emoji-aware (v4) behaviour to a "natural" line spacing behaviour constant in JavaScript.
Connect sketch-hq/Sketch#24338

Accommodate Sketch model change that adds a new text layer line spacing behaviour

---

docs/api/SymbolInstance.md

There were two anchors for resizing a symbolInstance to match the auto layout (“both were `#trigger-a-smart-layout`. I tweaked the heading so that the anchors weren’t matching anymore.

Fix duplicate anchor
